# Generated by Django 4.0.2 on 2022-02-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=100)),
                ('mytitle', models.CharField(max_length=500)),
                ('mycontent', models.CharField(max_length=1000)),
                ('mydate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=100)),
                ('mypassword', models.CharField(max_length=100)),
                ('myemail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50, unique=True)),
                ('userPW', models.CharField(max_length=1000)),
                ('userName', models.CharField(max_length=50)),
                ('userbirthDay', models.CharField(max_length=50)),
                ('userGender', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=50, unique=True)),
                ('userPhone', models.CharField(max_length=50, unique=True)),
                ('userAttitude', models.CharField(max_length=50)),
                ('startDay', models.DateField()),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
